# Starter pipeline
- task: Security static source code analysis@88
  inputs:
    CheckmarxService: 'checkmarx'
    projectName: 'SampleProject'
    preset: 'Checkmarx Default'
    fullTeamName: 'TeamName'
    incScan: true
    high: '4'
    medium: '5'
    low: '44'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
